### ISSUE TITLE
/src/painter-wepy.js" is not defined

### ISSUE THREAD

**Issue by trancelover** [hjyue1/painter-wepy#2]
module "npm/painter-wepy/src/painter-wepy.js" is not defined 
 Error: module "npm/painter-wepy/src/painter-wepy.js" is not defined
编译之后总是报这个错误，希望楼主解决一下！

**Comment by hjyue1** [comment]
@trancelover 确认下依赖包有安装吗？

**Comment by trancelover** [comment]
您好，装了，看起来是经过小程序开发工具编译之后生成的路径 差了一个 src 目录
如果 painter-wepy.wpy 放在 src 上一级目录应该就没问题了。
现在是直接把 /painter-wepy/ 目录放到 小程序的 /components/ 目录下
通过  import Painter from '../components/painter-wepy/src/painter-wepy'; 的方式引入的
直接npm 安装，编译还是报错。

**Comment by hjyue1** [comment]
@trancelover 我发布了1.0.6版本，麻烦您更新下看看是否能解决您的问题
