### ISSUE TITLE
编译的时候提示缺少文件

### ISSUE THREAD

**Issue by yoder** [hjyue1/painter-wepy#3]
[Error] Missing files: ./lib/util in E:\xxx\node_modules\painter-wepy\lib\painter-wepy.wpy
编译的时候提示缺少文件

**Comment by yoder** [comment]
手动修改\painter-wepy\lib\painter-wepy.wpy 里面相关路径即可。。。

**Comment by hjyue1** [comment]
@yoder 我发布了1.0.7版本, 修改了相关路径，感谢反馈
